name: SonarCloud Analysis

on:
  push:
    branches: 
    - master
    - dev
    - 'feature/**'
    - 'fix/**'
  pull_request:
    branches: [ master, dev ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    name: Running Google Java Formatting
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      # Recommended: latest versions of Google Java Format require JDK 11+
      - uses: actions/setup-java@v1
        with:
          java-version: "14"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"

  test:
    runs-on: ubuntu-latest
    name: Compile & test
    needs: formatting
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run all tests with SonarScan
        run: mvn -B clean verify -Psonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
